spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        ddl-auto: create
      jakarta:
        persistence:
          query:
            timeout: 5000
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

aws:
  s3:
    bucket: QWER
    url: ASDF
